-- MySQL Script generated by MySQL Workbench
-- zo 19 mrt 2017 17:02:35 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema GA_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `GA_db` ;

-- -----------------------------------------------------
-- Schema GA_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GA_db` DEFAULT CHARACTER SET utf8 ;
USE `GA_db` ;

-- -----------------------------------------------------
-- Table `GA_db`.`Templates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GA_db`.`Templates` ;

CREATE TABLE IF NOT EXISTS `GA_db`.`Templates` (
  `TemplateName` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`TemplateName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GA_db`.`Page`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GA_db`.`Page` ;

CREATE TABLE IF NOT EXISTS `GA_db`.`Page` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(255) NOT NULL,
  `Link` VARCHAR(255) NOT NULL,
  `Title` VARCHAR(255) NOT NULL,
  `TemplateName` VARCHAR(255) NOT NULL,
  `Visible` TINYINT NULL,
  `UnderConstruction` TINYINT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Page_Templates1_idx` (`TemplateName` ASC),
  CONSTRAINT `fk_Page_Templates1`
    FOREIGN KEY (`TemplateName`)
    REFERENCES `GA_db`.`Templates` (`TemplateName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GA_db`.`MenuBar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GA_db`.`MenuBar` ;

CREATE TABLE IF NOT EXISTS `GA_db`.`MenuBar` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Parent` INT NULL,
  `Page_ID` INT NOT NULL,
  `Visible` TINYINT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_MenuBar_MenuBar_idx` (`Parent` ASC),
  INDEX `fk_MenuBar_Page1_idx` (`Page_ID` ASC),
  CONSTRAINT `fk_MenuBar_MenuBar`
    FOREIGN KEY (`Parent`)
    REFERENCES `GA_db`.`MenuBar` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MenuBar_Page1`
    FOREIGN KEY (`Page_ID`)
    REFERENCES `GA_db`.`Page` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GA_db`.`Block`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GA_db`.`Block` ;

CREATE TABLE IF NOT EXISTS `GA_db`.`Block` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GA_db`.`Page_Has_blocks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GA_db`.`Page_Has_blocks` ;

CREATE TABLE IF NOT EXISTS `GA_db`.`Page_Has_blocks` (
  `Block_ID` INT NOT NULL,
  `Page_ID` INT NOT NULL,
  `Position` INT NOT NULL,
  PRIMARY KEY (`Block_ID`, `Page_ID`, `Position`),
  INDEX `fk_Block_has_Page_Page1_idx` (`Page_ID` ASC),
  INDEX `fk_Block_has_Page_Block1_idx` (`Block_ID` ASC),
  CONSTRAINT `fk_Block_has_Page_Block1`
    FOREIGN KEY (`Block_ID`)
    REFERENCES `GA_db`.`Block` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Block_has_Page_Page1`
    FOREIGN KEY (`Page_ID`)
    REFERENCES `GA_db`.`Page` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GA_db`.`ContentType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GA_db`.`ContentType` ;

CREATE TABLE IF NOT EXISTS `GA_db`.`ContentType` (
  `Type` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GA_db`.`Content`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GA_db`.`Content` ;

CREATE TABLE IF NOT EXISTS `GA_db`.`Content` (
  `ID` INT NOT NULL,
  `Content` LONGTEXT NULL,
  `ContentType` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Content_ContentType1_idx` (`ContentType` ASC),
  CONSTRAINT `fk_Content_ContentType1`
    FOREIGN KEY (`ContentType`)
    REFERENCES `GA_db`.`ContentType` (`Type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GA_db`.`Block_has_Content`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GA_db`.`Block_has_Content` ;

CREATE TABLE IF NOT EXISTS `GA_db`.`Block_has_Content` (
  `Block_ID` INT NOT NULL,
  `Content_ID` INT NOT NULL,
  `Position` INT NOT NULL,
  PRIMARY KEY (`Block_ID`, `Content_ID`, `Position`),
  INDEX `fk_Block_has_Content_Content1_idx` (`Content_ID` ASC),
  INDEX `fk_Block_has_Content_Block1_idx` (`Block_ID` ASC),
  CONSTRAINT `fk_Block_has_Content_Block1`
    FOREIGN KEY (`Block_ID`)
    REFERENCES `GA_db`.`Block` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Block_has_Content_Content1`
    FOREIGN KEY (`Content_ID`)
    REFERENCES `GA_db`.`Content` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GA_db`.`NewsArticle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GA_db`.`NewsArticle` ;

CREATE TABLE IF NOT EXISTS `GA_db`.`NewsArticle` (
  `ID` INT NOT NULL,
  `Title` VARCHAR(255) NOT NULL,
  `Image` VARCHAR(255) NULL,
  `Description` LONGTEXT NOT NULL,
  `Text` LONGTEXT NOT NULL,
  `Date` DATE NOT NULL,
  `Visible` TINYINT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GA_db`.`Workshop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GA_db`.`Workshop` ;

CREATE TABLE IF NOT EXISTS `GA_db`.`Workshop` (
  `ID` INT NOT NULL,
  `Date` DATE NOT NULL,
  `Title` VARCHAR(255) NOT NULL,
  `Description` LONGTEXT NULL,
  `Text` LONGTEXT NULL,
  `Visible` TINYINT NULL,
  `Duration` VARCHAR(255) NULL,
  `Cost` FLOAT NULL,
  `Template` INT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GA_db`.`Permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GA_db`.`Permissions` ;

CREATE TABLE IF NOT EXISTS `GA_db`.`Permissions` (
  `Permission` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Permission`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GA_db`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GA_db`.`Users` ;

CREATE TABLE IF NOT EXISTS `GA_db`.`Users` (
  `ID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Adress` VARCHAR(45) NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Permission` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Users_Permisions1_idx` (`Permission` ASC),
  CONSTRAINT `fk_Users_Permisions1`
    FOREIGN KEY (`Permission`)
    REFERENCES `GA_db`.`Permissions` (`Permission`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GA_db`.`Friends`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GA_db`.`Friends` ;

CREATE TABLE IF NOT EXISTS `GA_db`.`Friends` (
  `Users_ID` INT NOT NULL,
  `StartDate` DATE NULL,
  `EndDate` DATE NULL,
  INDEX `fk_Vrienden_Users1_idx` (`Users_ID` ASC),
  PRIMARY KEY (`Users_ID`),
  CONSTRAINT `fk_Vrienden_Users1`
    FOREIGN KEY (`Users_ID`)
    REFERENCES `GA_db`.`Users` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `GA_db`.`Templates`
-- -----------------------------------------------------
START TRANSACTION;
USE `GA_db`;
INSERT INTO `GA_db`.`Templates` (`TemplateName`) VALUES ('generic');
INSERT INTO `GA_db`.`Templates` (`TemplateName`) VALUES ('news');
INSERT INTO `GA_db`.`Templates` (`TemplateName`) VALUES ('product');

COMMIT;


-- -----------------------------------------------------
-- Data for table `GA_db`.`Page`
-- -----------------------------------------------------
START TRANSACTION;
USE `GA_db`;
INSERT INTO `GA_db`.`Page` (`ID`, `Name`, `Link`, `Title`, `TemplateName`, `Visible`, `UnderConstruction`) VALUES (1, 'Home', 'Home.blade.php', 'Home', 'generic', 1, 0);
INSERT INTO `GA_db`.`Page` (`ID`, `Name`, `Link`, `Title`, `TemplateName`, `Visible`, `UnderConstruction`) VALUES (2, 'Agenda', 'Agenda.blade.php', 'Agenda', 'generic', 1, NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `GA_db`.`MenuBar`
-- -----------------------------------------------------
START TRANSACTION;
USE `GA_db`;
INSERT INTO `GA_db`.`MenuBar` (`ID`, `Parent`, `Page_ID`, `Visible`) VALUES (1, NULL, 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `GA_db`.`ContentType`
-- -----------------------------------------------------
START TRANSACTION;
USE `GA_db`;
INSERT INTO `GA_db`.`ContentType` (`Type`) VALUES ('text');
INSERT INTO `GA_db`.`ContentType` (`Type`) VALUES ('image');
INSERT INTO `GA_db`.`ContentType` (`Type`) VALUES ('carousel');
INSERT INTO `GA_db`.`ContentType` (`Type`) VALUES ('title');

COMMIT;


-- -----------------------------------------------------
-- Data for table `GA_db`.`Permissions`
-- -----------------------------------------------------
START TRANSACTION;
USE `GA_db`;
INSERT INTO `GA_db`.`Permissions` (`Permission`) VALUES ('admin');
INSERT INTO `GA_db`.`Permissions` (`Permission`) VALUES ('user');
INSERT INTO `GA_db`.`Permissions` (`Permission`) VALUES ('moderator');

COMMIT;

